[package]
name = "libconfig-rs"
version = "1.0.5"
edition = "2021"

description = "libconfig parser in rust"
documentation = "https://docs.rs/libconfig-rs"
readme = "README.md"
license = "0BSD"
repository = "https://github.com/JoNil/libconfig-rs"

[dependencies]
nom = "7"
indexmap = "1"